
# pipelines:
#   branches:
#     main:
      # - step:
      #     name: Deploy to staging
      #     deployment: staging
      #     script:
      #       - cat ./staging-deploy.sh | ssh -T root@64.226.99.238
      #       - echo "Deployment finished!"


      # - step:
      #   name: Deploy to staging
      #   deployment: staging
      #   script:
      #   - pipe: atlassian/ssh-run:0.4.1
      #     variables:
      #       SSH_USER: 'root'
      #       SERVER: '64.226.99.238'
      #       MODE: 'script'
      #       COMMAND: 'staging-deploy.sh'
      #       ENV_VARS: >-
      #         OVERWRITE_ENVIRONMENT='staging'

pipelines:
  branches:
    main:
      - step:
          name: Deploy to staging
          deployment: staging
          script:
          - pipe: atlassian/ssh-run:0.4.1
            variables:
              SSH_USER: 'root'
              SERVER: '64.226.99.238'
              MODE: 'script'
              COMMAND: 'staging-deploy.sh'
              ENV_VARS: >-
                OVERWRITE_ENVIRONMENT='staging'